import type { Metadata } from 'next';
import '../styles/globals.css';
import { Providers } from '../components/globals/ui/Provider';
import { ThemeProvider } from '@/components/globals/ui/ThemeContext';
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { Roboto, Roboto_Mono } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-roboto-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${robotoMono.variable}`}>
      <body className="font-sans bg-background text-foreground" suppressHydrationWarning>
        <Providers>
          <ThemeProvider>
            <SpeedInsights/>
            <Analytics/>
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
