import type { Metadata } from 'next';
import '../styles/globals.css';
import { Providers } from '../components/globals/ui/Providers';
import { ThemeProvider } from '@/components/globals/ui/ThemeContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load Roboto and Roboto Mono from Google Fonts */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Roboto+Mono:wght@400;500&display=swap"
        />
      </head>
      <body className="font-sans bg-background text-foreground" suppressHydrationWarning>
      <Providers>
        <ThemeProvider>
          {children}
        </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}